server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderflow_orders
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    producer:
      properties:
        spring.json.type.mapping: "orderCancelled:com.orderflow.order.event.OrderCancelledEvent"
    consumer:
      properties:
        spring.json.type.mapping: "stockReleased:com.orderflow.order.event.StockReleasedEvent, paymentRefunded:com.orderflow.order.event.PaymentRefundedEvent"